version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout

      - run:
        name: Install dependencies
        command: |
          python -m pip install --upgrade pip
          pip install tox

      - run:
        name: Export Gemfury credentials from env
        command: |
          echo "GEMFURY_USERNAME=$GEMFURY_USERNAME" >> .env
          echo "GEMFURY_PASSWORD=$GEMFURY_PASSWORD" >> .env

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build-image:
          requires:
            - test
