version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install tox

      - run:
          name: Export Gemfury credentials from env
          command: |
            echo "GEMFURY_USERNAME=$GEMFURY_USERNAME" >> .env
            echo "GEMFURY_PASSWORD=$GEMFURY_PASSWORD" >> .env

      - run:
          name: Run tox
          command: ./run_tests_with_env.sh

  build-and-push:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - run:
          name: Build & tag Docker image
          command: |
            TAG=${CIRCLE_BRANCH//[^a-zA-Z0-9_.-]/-}
            IMAGE_TAG=nb2prod-api-service:$TAG
            docker build -t "$DOCKER_USER/$IMAGE_TAG" .
            docker tag "$DOCKER_USER/$IMAGE_TAG" "$DOCKER_USER/nb2prod-api-service:latest"

      - run:
          name: Push Docker image
          command: |
            docker push "$DOCKER_USER/nb2prod-api-service:${CIRCLE_BRANCH}"
            docker push "$DOCKER_USER/nb2prod-api-service:latest"

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          # filters:
          #   branches:
          #     only:
          #       - main
